stages:
  - test
  - staging
  - production

before_script:
  - apt-get update -qy

test:
  stage: test
  image: python:latest
  script:
    - apt-get install -y libpq-dev
    - pip install -r requirements.txt
    - cd server
    - python manage.py test tests
    - echo "Done"

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
