stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - echo "Checking python versions."
    - python3 -V
    - python -V
    - cd server
    - pip install -r requirements.txt
    - echo "Done"

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
