image: node:latest

stages:
  - test
  - staging
  - production

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

test:
  stage: test
  script:
    - apt-get update -qy
    - echo "Install python3."
    - apt-get install -y python3-pip python3-dev
    - echo "Install the required python packages."
    - cd server
    - pip3 install -r requirements.txt
    - python3 manage.py test tests
    - echo "Done"

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
