stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - cd server
    - pip install -r requirements.txt
    - echo "Done"

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
