image: nikolaik/python-nodejs:latest

stages:
  - test
  - staging
  - production

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev libpq-dev
  - gem install dpl
  - cd server
  - pip3 install -r requirements.txt
  - cd ..

test:
  stage: test
  script:
    - cd server
    - python3 manage.py test tests
    - echo "Done"

staging:
  type: deploy
  stage: staging
  script:
    - cd client
    - npm i
    - npm build
    - cd ../server
    - python3 manage.py collectstatic
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  type: deploy
  stage: production
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
