stages:
  - test
  - staging
  - production

test-server:
  stage: test
  image: python:latest
  variables:
    - DEBUG: 'False'
  before_script:
    - apt-get update -qy
  script:
    - pip install -r requirements.txt
    - cd server
    - python manage.py test
    - echo "Done"

test-client:
  stage: test
  image: node:lts-stretch
  before_script:
    - apt-get update -qy
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - cd client
    - npm ci
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  before_script:
    - apt-get update -qy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  type: deploy
  stage: production
  image: ruby:latest
  before_script:
    - apt-get update -qy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
