# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.5.1
  python: circleci/python@1.4.0
  browser-tools: circleci/browser-tools@1.1.3
  heroku: circleci/heroku@1.2

jobs:
  test-server:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run: cd server && python manage.py test
  
  test-client:
    docker:
      - image: cimg/node:16.4.0-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: cd client && npm ci
      - run: cd client && npm run test -- --no-watch --no-progress
  
  staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_STAGING_APP_NAME

  production:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_PRODUCTION_APP_NAME

workflows:
  test-staging-production:
    jobs:
      - test-server
      - test-client
      - staging:
          requires:
            - test-server
            - test-client
          filters:
            branches:
              only:
                - staging
      - production:
          requires:
            - test-server
            - test-client
          filters:
            branches:
              only:
                - master
