# Generated by Django 3.2 on 2021-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.TextField(default='', primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True, default='')),
            ],
        ),
    ]
