# Generated by Django 3.2 on 2021-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_plans', '0003_alter_courseplan_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
