# Generated by Django 3.2 on 2021-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_plans', '0004_auto_20210505_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
