# Generated by Django 3.2 on 2021-05-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_plans', '0005_alter_courseplan_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
