# Generated by Django 3.2 on 2021-05-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_plans', '0006_alter_courseplan_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
    ]
